print:
	g++ -std=c++11 -O3 ./main.cpp -lboost_program_options
	./a.out --eval --maxN 10  --print
eval:
	g++ -std=c++11 -O3 ./main.cpp -lboost_program_options
	./a.out --eval --maxN 10

debug:
	g++ -g -std=c++11 ./main.cpp  -lboost_program_options
	gdb ./a.out 
clean:
	./a.out
